import java.util.*;
import net.mindview.util.*;


public class Ch17ex01 {

	public static void main(String[] args) {
		List<String> arrayList = new ArrayList<String>();
		for(int i = 0; i < Countries.DATA.length; i++) {
			arrayList.add(Countries.DATA[i][0]);
		}	
		List<String> linkedList = new LinkedList<String>();
		for(int i = 0; i < Countries.DATA.length; i++) {
			linkedList.add(Countries.DATA[i][1]);
		}
		System.out.println(arrayList);
		System.out.println(linkedList);
		Collections.sort(arrayList);
		Collections.sort(linkedList);
		System.out.println("Sorted countries: " + arrayList);
		System.out.println("Sorted capitals: " + linkedList);
		for(int i = 0; i < 3; i++) {
			Collections.shuffle(arrayList);
			Collections.shuffle(linkedList);
			System.out.println("Shuffled countries: " + arrayList);
			System.out.println("Shuffled capitals: " + linkedList);
		}
		
	}

}

/* Output:
[ALGERIA, ANGOLA, BENIN, BOTSWANA, BURKINA FASO, BURUNDI, CAMEROON, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, CHAD, COMOROS, CONGO, DJIBOUTI, EGYPT, EQUATORIAL GUINEA, ERITREA, ETHIOPIA, GABON, THE GAMBIA, GHANA, GUINEA, BISSAU, COTE D'IVOIR (IVORY COAST), KENYA, LESOTHO, LIBERIA, LIBYA, MADAGASCAR, MALAWI, MALI, MAURITANIA, MAURITIUS, MOROCCO, MOZAMBIQUE, NAMIBIA, NIGER, NIGERIA, RWANDA, SAO TOME E PRINCIPE, SENEGAL, SEYCHELLES, SIERRA LEONE, SOMALIA, SOUTH AFRICA, SUDAN, SWAZILAND, TANZANIA, TOGO, TUNISIA, UGANDA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), ZAMBIA, ZIMBABWE, AFGHANISTAN, BAHRAIN, BANGLADESH, BHUTAN, BRUNEI, CAMBODIA, CHINA, CYPRUS, INDIA, INDONESIA, IRAN, IRAQ, ISRAEL, JAPAN, JORDAN, KUWAIT, LAOS, LEBANON, MALAYSIA, THE MALDIVES, MONGOLIA, MYANMAR (BURMA), NEPAL, NORTH KOREA, OMAN, PAKISTAN, PHILIPPINES, QATAR, SAUDI ARABIA, SINGAPORE, SOUTH KOREA, SRI LANKA, SYRIA, TAIWAN (REPUBLIC OF CHINA), THAILAND, TURKEY, UNITED ARAB EMIRATES, VIETNAM, YEMEN, AUSTRALIA, FIJI, KIRIBATI, MARSHALL ISLANDS, MICRONESIA, NAURU, NEW ZEALAND, PALAU, PAPUA NEW GUINEA, SOLOMON ISLANDS, TONGA, TUVALU, VANUATU, WESTERN SAMOA, ARMENIA, AZERBAIJAN, BELARUS (BYELORUSSIA), BULGARIA, GEORGIA, KAZAKSTAN, KYRGYZSTAN, MOLDOVA, RUSSIA, TAJIKISTAN, TURKMENISTAN, UKRAINE, UZBEKISTAN, ALBANIA, ANDORRA, AUSTRIA, BELGIUM, BOSNIA, HERZEGOVINA, CROATIA, CZECH REPUBLIC, DENMARK, ESTONIA, FINLAND, FRANCE, GERMANY, GREECE, HUNGARY, ICELAND, IRELAND, ITALY, LATVIA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MALTA, MONACO, MONTENEGRO, THE NETHERLANDS, NORWAY, POLAND, PORTUGAL, ROMANIA, SAN MARINO, SERBIA, SLOVAKIA, SLOVENIA, SPAIN, SWEDEN, SWITZERLAND, UNITED KINGDOM, VATICAN CITY, ANTIGUA AND BARBUDA, BAHAMAS, BARBADOS, BELIZE, CANADA, COSTA RICA, CUBA, DOMINICA, DOMINICAN REPUBLIC, EL SALVADOR, GRENADA, GUATEMALA, HAITI, HONDURAS, JAMAICA, MEXICO, NICARAGUA, PANAMA, ST. KITTS, NEVIS, ST. LUCIA, ST. VINCENT AND THE GRENADINES, UNITED STATES OF AMERICA, ARGENTINA, BOLIVIA, BRAZIL, CHILE, COLOMBIA, ECUADOR, GUYANA, PARAGUAY, PERU, SURINAME, TRINIDAD AND TOBAGO, URUGUAY, VENEZUELA]
[Algiers, Luanda, Porto-Novo, Gaberone, Ouagadougou, Bujumbura, Yaounde, Praia, Bangui, N'djamena, Moroni, Brazzaville, Dijibouti, Cairo, Malabo, Asmara, Addis Ababa, Libreville, Banjul, Accra, Conakry, Bissau, Yamoussoukro, Nairobi, Maseru, Monrovia, Tripoli, Antananarivo, Lilongwe, Bamako, Nouakchott, Port Louis, Rabat, Maputo, Windhoek, Niamey, Abuja, Kigali, Sao Tome, Dakar, Victoria, Freetown, Mogadishu, Pretoria/Cape Town, Khartoum, Mbabane, Dodoma, Lome, Tunis, Kampala, Kinshasa, Lusaka, Harare, Kabul, Manama, Dhaka, Thimphu, Bandar Seri Begawan, Phnom Penh, Beijing, Nicosia, New Delhi, Jakarta, Tehran, Baghdad, Jerusalem, Tokyo, Amman, Kuwait City, Vientiane, Beirut, Kuala Lumpur, Male, Ulan Bator, Rangoon, Katmandu, P'yongyang, Muscat, Islamabad, Manila, Doha, Riyadh, Singapore, Seoul, Colombo, Damascus, Taipei, Bangkok, Ankara, Abu Dhabi, Hanoi, Sana'a, Canberra, Suva, Bairiki, Dalap-Uliga-Darrit, Palikir, Yaren, Wellington, Koror, Port Moresby, Honaira, Nuku'alofa, Fongafale, < Port-Vila, Apia, Yerevan, Baku, Minsk, Sofia, Tbilisi, Almaty, Alma-Ata, Chisinau, Moscow, Dushanbe, Ashkabad, Kyiv, Tashkent, Tirana, Andorra la Vella, Vienna, Brussels, -, Sarajevo, Zagreb, Prague, Copenhagen, Tallinn, Helsinki, Paris, Berlin, Athens, Budapest, Reykjavik, Dublin, Rome, Riga, Vaduz, Vilnius, Luxembourg, Skopje, Valletta, Monaco, Podgorica, Amsterdam, Oslo, Warsaw, Lisbon, Bucharest, San Marino, Belgrade, Bratislava, Ljuijana, Madrid, Stockholm, Berne, London, ---, Saint John's, Nassau, Bridgetown, Belmopan, Ottawa, San Jose, Havana, Roseau, Santo Domingo, San Salvador, Saint George's, Guatemala City, Port-au-Prince, Tegucigalpa, Kingston, Mexico City, Managua, Panama City, -, Basseterre, Castries, Kingstown, Washington, D.C., Buenos Aires, Sucre (legal)/La Paz(administrative), Brasilia, Santiago, Bogota, Quito, Georgetown, Asuncion, Lima, Paramaribo, Port of Spain, Montevideo, Caracas]
Sorted countries: [AFGHANISTAN, ALBANIA, ALGERIA, ANDORRA, ANGOLA, ANTIGUA AND BARBUDA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIJAN, BAHAMAS, BAHRAIN, BANGLADESH, BARBADOS, BELARUS (BYELORUSSIA), BELGIUM, BELIZE, BENIN, BHUTAN, BISSAU, BOLIVIA, BOSNIA, BOTSWANA, BRAZIL, BRUNEI, BULGARIA, BURKINA FASO, BURUNDI, CAMBODIA, CAMEROON, CANADA, CAPE VERDE, CENTRAL AFRICAN REPUBLIC, CHAD, CHILE, CHINA, COLOMBIA, COMOROS, CONGO, COSTA RICA, COTE D'IVOIR (IVORY COAST), CROATIA, CUBA, CYPRUS, CZECH REPUBLIC, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), DENMARK, DJIBOUTI, DOMINICA, DOMINICAN REPUBLIC, ECUADOR, EGYPT, EL SALVADOR, EQUATORIAL GUINEA, ERITREA, ESTONIA, ETHIOPIA, FIJI, FINLAND, FRANCE, GABON, GEORGIA, GERMANY, GHANA, GREECE, GRENADA, GUATEMALA, GUINEA, GUYANA, HAITI, HERZEGOVINA, HONDURAS, HUNGARY, ICELAND, INDIA, INDONESIA, IRAN, IRAQ, IRELAND, ISRAEL, ITALY, JAMAICA, JAPAN, JORDAN, KAZAKSTAN, KENYA, KIRIBATI, KUWAIT, KYRGYZSTAN, LAOS, LATVIA, LEBANON, LESOTHO, LIBERIA, LIBYA, LIECHTENSTEIN, LITHUANIA, LUXEMBOURG, MACEDONIA, MADAGASCAR, MALAWI, MALAYSIA, MALI, MALTA, MARSHALL ISLANDS, MAURITANIA, MAURITIUS, MEXICO, MICRONESIA, MOLDOVA, MONACO, MONGOLIA, MONTENEGRO, MOROCCO, MOZAMBIQUE, MYANMAR (BURMA), NAMIBIA, NAURU, NEPAL, NEVIS, NEW ZEALAND, NICARAGUA, NIGER, NIGERIA, NORTH KOREA, NORWAY, OMAN, PAKISTAN, PALAU, PANAMA, PAPUA NEW GUINEA, PARAGUAY, PERU, PHILIPPINES, POLAND, PORTUGAL, QATAR, ROMANIA, RUSSIA, RWANDA, SAN MARINO, SAO TOME E PRINCIPE, SAUDI ARABIA, SENEGAL, SERBIA, SEYCHELLES, SIERRA LEONE, SINGAPORE, SLOVAKIA, SLOVENIA, SOLOMON ISLANDS, SOMALIA, SOUTH AFRICA, SOUTH KOREA, SPAIN, SRI LANKA, ST. KITTS, ST. LUCIA, ST. VINCENT AND THE GRENADINES, SUDAN, SURINAME, SWAZILAND, SWEDEN, SWITZERLAND, SYRIA, TAIWAN (REPUBLIC OF CHINA), TAJIKISTAN, TANZANIA, THAILAND, THE GAMBIA, THE MALDIVES, THE NETHERLANDS, TOGO, TONGA, TRINIDAD AND TOBAGO, TUNISIA, TURKEY, TURKMENISTAN, TUVALU, UGANDA, UKRAINE, UNITED ARAB EMIRATES, UNITED KINGDOM, UNITED STATES OF AMERICA, URUGUAY, UZBEKISTAN, VANUATU, VATICAN CITY, VENEZUELA, VIETNAM, WESTERN SAMOA, YEMEN, ZAMBIA, ZIMBABWE]
Sorted capitals: [-, -, ---, < Port-Vila, Abu Dhabi, Abuja, Accra, Addis Ababa, Algiers, Alma-Ata, Almaty, Amman, Amsterdam, Andorra la Vella, Ankara, Antananarivo, Apia, Ashkabad, Asmara, Asuncion, Athens, Baghdad, Bairiki, Baku, Bamako, Bandar Seri Begawan, Bangkok, Bangui, Banjul, Basseterre, Beijing, Beirut, Belgrade, Belmopan, Berlin, Berne, Bissau, Bogota, Brasilia, Bratislava, Brazzaville, Bridgetown, Brussels, Bucharest, Budapest, Buenos Aires, Bujumbura, Cairo, Canberra, Caracas, Castries, Chisinau, Colombo, Conakry, Copenhagen, Dakar, Dalap-Uliga-Darrit, Damascus, Dhaka, Dijibouti, Dodoma, Doha, Dublin, Dushanbe, Fongafale, Freetown, Gaberone, Georgetown, Guatemala City, Hanoi, Harare, Havana, Helsinki, Honaira, Islamabad, Jakarta, Jerusalem, Kabul, Kampala, Katmandu, Khartoum, Kigali, Kingston, Kingstown, Kinshasa, Koror, Kuala Lumpur, Kuwait City, Kyiv, Libreville, Lilongwe, Lima, Lisbon, Ljuijana, Lome, London, Luanda, Lusaka, Luxembourg, Madrid, Malabo, Male, Managua, Manama, Manila, Maputo, Maseru, Mbabane, Mexico City, Minsk, Mogadishu, Monaco, Monrovia, Montevideo, Moroni, Moscow, Muscat, N'djamena, Nairobi, Nassau, New Delhi, Niamey, Nicosia, Nouakchott, Nuku'alofa, Oslo, Ottawa, Ouagadougou, P'yongyang, Palikir, Panama City, Paramaribo, Paris, Phnom Penh, Podgorica, Port Louis, Port Moresby, Port of Spain, Port-au-Prince, Porto-Novo, Prague, Praia, Pretoria/Cape Town, Quito, Rabat, Rangoon, Reykjavik, Riga, Riyadh, Rome, Roseau, Saint George's, Saint John's, San Jose, San Marino, San Salvador, Sana'a, Santiago, Santo Domingo, Sao Tome, Sarajevo, Seoul, Singapore, Skopje, Sofia, Stockholm, Sucre (legal)/La Paz(administrative), Suva, Taipei, Tallinn, Tashkent, Tbilisi, Tegucigalpa, Tehran, Thimphu, Tirana, Tokyo, Tripoli, Tunis, Ulan Bator, Vaduz, Valletta, Victoria, Vienna, Vientiane, Vilnius, Warsaw, Washington, D.C., Wellington, Windhoek, Yamoussoukro, Yaounde, Yaren, Yerevan, Zagreb]
Shuffled countries: [COTE D'IVOIR (IVORY COAST), LEBANON, ZIMBABWE, MAURITANIA, MALAYSIA, SAUDI ARABIA, AZERBAIJAN, GUINEA, SAN MARINO, MALAWI, KUWAIT, BOLIVIA, CONGO, DENMARK, UKRAINE, NAURU, SWAZILAND, BHUTAN, BISSAU, DJIBOUTI, CYPRUS, COMOROS, MALI, MOLDOVA, PHILIPPINES, CAMBODIA, NIGER, CROATIA, SENEGAL, OMAN, ARMENIA, SLOVAKIA, LIBYA, GABON, ST. KITTS, CHAD, RUSSIA, ST. LUCIA, GERMANY, HUNGARY, EL SALVADOR, SWITZERLAND, SAO TOME E PRINCIPE, TUNISIA, NORTH KOREA, KENYA, LAOS, SEYCHELLES, POLAND, NEVIS, MYANMAR (BURMA), JAMAICA, BOTSWANA, BENIN, BURUNDI, BURKINA FASO, GHANA, COSTA RICA, URUGUAY, SOUTH KOREA, SOMALIA, LATVIA, SINGAPORE, CENTRAL AFRICAN REPUBLIC, MADAGASCAR, TRINIDAD AND TOBAGO, LITHUANIA, PERU, LESOTHO, ALBANIA, PANAMA, MONACO, ROMANIA, MARSHALL ISLANDS, MAURITIUS, AUSTRALIA, JORDAN, BAHRAIN, PAPUA NEW GUINEA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), FINLAND, GEORGIA, SYRIA, THE MALDIVES, GUYANA, BELGIUM, DOMINICA, TAIWAN (REPUBLIC OF CHINA), VIETNAM, FRANCE, THAILAND, ESTONIA, SOLOMON ISLANDS, KYRGYZSTAN, ANDORRA, QATAR, TAJIKISTAN, BELARUS (BYELORUSSIA), HERZEGOVINA, CHILE, TURKMENISTAN, CUBA, TURKEY, SERBIA, YEMEN, NIGERIA, GRENADA, ITALY, CHINA, SOUTH AFRICA, TOGO, BANGLADESH, SPAIN, CZECH REPUBLIC, ISRAEL, BRAZIL, PAKISTAN, ANGOLA, ARGENTINA, LUXEMBOURG, UNITED STATES OF AMERICA, NEW ZEALAND, UGANDA, CAMEROON, ECUADOR, SWEDEN, THE GAMBIA, BARBADOS, NICARAGUA, LIBERIA, KIRIBATI, INDIA, THE NETHERLANDS, MACEDONIA, BULGARIA, SIERRA LEONE, IRAN, NORWAY, MONTENEGRO, VENEZUELA, IRELAND, MOZAMBIQUE, UZBEKISTAN, EGYPT, TONGA, RWANDA, BAHAMAS, EQUATORIAL GUINEA, INDONESIA, ST. VINCENT AND THE GRENADINES, MALTA, UNITED ARAB EMIRATES, VATICAN CITY, NEPAL, BRUNEI, HAITI, BELIZE, PORTUGAL, MONGOLIA, DOMINICAN REPUBLIC, PARAGUAY, NAMIBIA, PALAU, MOROCCO, HONDURAS, SURINAME, LIECHTENSTEIN, TANZANIA, MICRONESIA, SUDAN, AUSTRIA, GUATEMALA, BOSNIA, ALGERIA, TUVALU, CANADA, UNITED KINGDOM, IRAQ, SLOVENIA, ETHIOPIA, WESTERN SAMOA, ZAMBIA, AFGHANISTAN, SRI LANKA, VANUATU, JAPAN, GREECE, KAZAKSTAN, CAPE VERDE, ANTIGUA AND BARBUDA, COLOMBIA, ERITREA, ICELAND, MEXICO, FIJI]
Shuffled capitals: [Lisbon, Thimphu, Islamabad, Tripoli, Kyiv, Bridgetown, Ankara, Kingstown, Hanoi, -, N'djamena, Panama City, Koror, Nuku'alofa, Riyadh, Rangoon, New Delhi, London, Vaduz, Dodoma, Paramaribo, Vientiane, Belmopan, Vilnius, Port-au-Prince, Bangkok, San Salvador, Nicosia, Phnom Penh, Bogota, Tehran, Abu Dhabi, Oslo, Tegucigalpa, Yaren, Pretoria/Cape Town, Dijibouti, Kuala Lumpur, Berlin, Palikir, P'yongyang, Praia, Andorra la Vella, Freetown, Sao Tome, Copenhagen, Sucre (legal)/La Paz(administrative), Prague, Port Moresby, Kigali, Roseau, Reykjavik, Kampala, Brasilia, Windhoek, Luanda, Georgetown, Singapore, Ulan Bator, Sofia, Dublin, Beirut, Porto-Novo, Santo Domingo, Ouagadougou, Apia, Honaira, Brazzaville, Maseru, Bamako, Accra, Katmandu, Male, Manama, Bratislava, Almaty, Monrovia, Amsterdam, Bucharest, Yaounde, Podgorica, Niamey, Skopje, Quito, Amman, Baku, Libreville, Tallinn, Basseterre, Caracas, Guatemala City, Beijing, Manila, Taipei, Ljuijana, Bairiki, Lima, Saint George's, Seoul, Mbabane, Mogadishu, Abuja, Washington, D.C., Budapest, Canberra, Alma-Ata, Malabo, Banjul, Muscat, Port of Spain, Moroni, Minsk, Conakry, Ottawa, Maputo, Chisinau, Kabul, Sarajevo, Damascus, Suva, Sana'a, Nairobi, Bissau, Vienna, Tunis, Wellington, Moscow, Tokyo, Addis Ababa, Asmara, Riga, Castries, Colombo, Ashkabad, Dhaka, Antananarivo, Lome, Kingston, Khartoum, Nassau, < Port-Vila, Saint John's, Fongafale, Warsaw, Tashkent, Havana, Madrid, Yamoussoukro, Buenos Aires, Rome, Bujumbura, Athens, Victoria, Jerusalem, Lusaka, Berne, Bangui, Dalap-Uliga-Darrit, Baghdad, San Marino, Tirana, Yerevan, Santiago, San Jose, Doha, Brussels, Stockholm, ---, Port Louis, Gaberone, Montevideo, Jakarta, Tbilisi, Cairo, Zagreb, Rabat, Harare, Helsinki, Kuwait City, Paris, Belgrade, Lilongwe, Bandar Seri Begawan, Asuncion, Valletta, Mexico City, Managua, -, Dakar, Nouakchott, Algiers, Luxembourg, Dushanbe, Kinshasa, Monaco]
Shuffled countries: [PHILIPPINES, AFGHANISTAN, CHINA, BRAZIL, HERZEGOVINA, POLAND, URUGUAY, DENMARK, LAOS, CROATIA, NAMIBIA, BISSAU, UNITED STATES OF AMERICA, TAIWAN (REPUBLIC OF CHINA), LUXEMBOURG, ICELAND, BANGLADESH, QATAR, SEYCHELLES, THE NETHERLANDS, NEW ZEALAND, NEPAL, WESTERN SAMOA, GREECE, CHAD, SRI LANKA, CAMBODIA, RWANDA, BRUNEI, THE MALDIVES, LESOTHO, CYPRUS, PAPUA NEW GUINEA, SWAZILAND, NAURU, MALAYSIA, ERITREA, NICARAGUA, MICRONESIA, GUINEA, AUSTRIA, MOROCCO, LIBERIA, SIERRA LEONE, INDIA, UNITED ARAB EMIRATES, EGYPT, MEXICO, SINGAPORE, VIETNAM, RUSSIA, GUYANA, ETHIOPIA, MACEDONIA, TURKMENISTAN, ESTONIA, OMAN, SLOVENIA, BHUTAN, AZERBAIJAN, CAMEROON, PALAU, MAURITANIA, LIECHTENSTEIN, SLOVAKIA, UZBEKISTAN, KAZAKSTAN, ARGENTINA, MALTA, SAO TOME E PRINCIPE, IRAQ, ST. VINCENT AND THE GRENADINES, TOGO, MADAGASCAR, ZAMBIA, CONGO, PANAMA, BOSNIA, THE GAMBIA, NIGER, CENTRAL AFRICAN REPUBLIC, COTE D'IVOIR (IVORY COAST), YEMEN, GRENADA, UKRAINE, ALBANIA, MONTENEGRO, FIJI, TUVALU, BAHRAIN, LEBANON, BOLIVIA, EL SALVADOR, TONGA, ST. KITTS, HONDURAS, NEVIS, MONGOLIA, MALI, JORDAN, GEORGIA, ROMANIA, LIBYA, PAKISTAN, CANADA, THAILAND, ANDORRA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), ITALY, LATVIA, GUATEMALA, KUWAIT, JAPAN, BELGIUM, CHILE, MOZAMBIQUE, HUNGARY, BURUNDI, ISRAEL, CUBA, BELARUS (BYELORUSSIA), TANZANIA, BAHAMAS, BARBADOS, CZECH REPUBLIC, PARAGUAY, GHANA, DJIBOUTI, COMOROS, BELIZE, ZIMBABWE, GERMANY, SUDAN, JAMAICA, KENYA, EQUATORIAL GUINEA, ECUADOR, ANGOLA, INDONESIA, SERBIA, MAURITIUS, ARMENIA, NIGERIA, SWITZERLAND, AUSTRALIA, SPAIN, BULGARIA, SURINAME, SOUTH KOREA, MONACO, IRAN, UGANDA, HAITI, FRANCE, TURKEY, DOMINICA, VATICAN CITY, KIRIBATI, VANUATU, NORWAY, IRELAND, VENEZUELA, TRINIDAD AND TOBAGO, TUNISIA, GABON, PORTUGAL, BURKINA FASO, CAPE VERDE, ALGERIA, SAUDI ARABIA, SOUTH AFRICA, SOLOMON ISLANDS, SOMALIA, MALAWI, MARSHALL ISLANDS, COLOMBIA, KYRGYZSTAN, FINLAND, DOMINICAN REPUBLIC, MYANMAR (BURMA), SWEDEN, SYRIA, SENEGAL, ST. LUCIA, MOLDOVA, PERU, ANTIGUA AND BARBUDA, UNITED KINGDOM, BOTSWANA, BENIN, LITHUANIA, SAN MARINO, COSTA RICA, NORTH KOREA, TAJIKISTAN]
Shuffled capitals: [Honaira, Colombo, Manila, Praia, Yaounde, Dakar, Georgetown, Kingston, Prague, Brazzaville, Copenhagen, Stockholm, Libreville, Lome, Sucre (legal)/La Paz(administrative), Budapest, London, Nairobi, Palikir, Asmara, Fongafale, Tegucigalpa, Tbilisi, Montevideo, Victoria, Koror, Tirana, Bissau, Port of Spain, Santiago, Skopje, Kabul, Havana, Luanda, Monrovia, Amman, Kigali, Doha, Porto-Novo, Caracas, Alma-Ata, Maputo, Yerevan, Maseru, Algiers, Nassau, Banjul, Helsinki, Minsk, Manama, Port Moresby, Vienna, Bamako, Beirut, Kyiv, Bangui, Jerusalem, Sao Tome, Luxembourg, Ottawa, Yamoussoukro, < Port-Vila, Phnom Penh, Tokyo, Roseau, Berne, Lusaka, Oslo, Malabo, Harare, Abu Dhabi, Andorra la Vella, Madrid, Managua, Baghdad, Buenos Aires, Chisinau, Bogota, Yaren, Kingstown, Apia, Dushanbe, Ashkabad, N'djamena, Kuala Lumpur, Nicosia, Vilnius, Ouagadougou, Monaco, Moroni, Pretoria/Cape Town, Amsterdam, Islamabad, Berlin, ---, Conakry, Saint George's, Sarajevo, Nouakchott, Dalap-Uliga-Darrit, Reykjavik, Lisbon, Bandar Seri Begawan, Riga, Santo Domingo, Tehran, Ljuijana, Windhoek, Belmopan, Accra, Hanoi, Bangkok, Antananarivo, Bairiki, Quito, San Salvador, Khartoum, Ulan Bator, Mbabane, -, Bratislava, -, Mexico City, Belgrade, Beijing, Damascus, Cairo, Brasilia, Taipei, Sofia, Canberra, Male, Baku, Gaberone, Washington, D.C., New Delhi, Moscow, San Marino, Castries, Lima, Tallinn, Saint John's, Vaduz, Rabat, Tripoli, Niamey, Brussels, Kampala, P'yongyang, Port Louis, Thimphu, Riyadh, Rangoon, Seoul, Podgorica, Addis Ababa, Valletta, Bucharest, Basseterre, Singapore, Vientiane, Warsaw, Dodoma, Ankara, Asuncion, Tashkent, Nuku'alofa, Mogadishu, Kuwait City, Freetown, Paris, Wellington, Jakarta, Paramaribo, San Jose, Dublin, Guatemala City, Suva, Athens, Kinshasa, Port-au-Prince, Katmandu, Lilongwe, Panama City, Muscat, Dhaka, Tunis, Rome, Almaty, Sana'a, Zagreb, Dijibouti, Bujumbura, Abuja, Bridgetown]
Shuffled countries: [BENIN, BELIZE, DOMINICAN REPUBLIC, ST. KITTS, ALGERIA, BULGARIA, DEMOCRATIC REPUBLIC OF THE CONGO (ZAIRE), TUNISIA, LIBERIA, ZIMBABWE, ISRAEL, COSTA RICA, ALBANIA, BAHRAIN, AUSTRALIA, SOUTH AFRICA, TAJIKISTAN, FRANCE, BANGLADESH, COMOROS, NIGER, MOZAMBIQUE, KIRIBATI, CONGO, BURUNDI, MARSHALL ISLANDS, URUGUAY, COTE D'IVOIR (IVORY COAST), SLOVAKIA, BELGIUM, MALAWI, AFGHANISTAN, MYANMAR (BURMA), SENEGAL, PAKISTAN, JAPAN, SEYCHELLES, NEPAL, LITHUANIA, ECUADOR, BURKINA FASO, SWEDEN, BAHAMAS, UNITED KINGDOM, SOLOMON ISLANDS, JAMAICA, KUWAIT, ANGOLA, CZECH REPUBLIC, MEXICO, MADAGASCAR, MALTA, MONACO, HAITI, EL SALVADOR, MAURITANIA, NAURU, SINGAPORE, AUSTRIA, HERZEGOVINA, VATICAN CITY, SERBIA, PARAGUAY, LUXEMBOURG, GUATEMALA, TANZANIA, PERU, OMAN, VIETNAM, TONGA, ETHIOPIA, ARGENTINA, TRINIDAD AND TOBAGO, QATAR, COLOMBIA, SUDAN, LEBANON, VANUATU, NEVIS, CAPE VERDE, BOLIVIA, ST. LUCIA, BRAZIL, VENEZUELA, SOMALIA, THE MALDIVES, SOUTH KOREA, SPAIN, SAUDI ARABIA, CUBA, SWITZERLAND, TURKMENISTAN, SYRIA, HONDURAS, GREECE, ANDORRA, AZERBAIJAN, MOLDOVA, CAMEROON, FINLAND, MICRONESIA, IRAQ, ANTIGUA AND BARBUDA, SRI LANKA, IRAN, ICELAND, UZBEKISTAN, SLOVENIA, CAMBODIA, NAMIBIA, SAN MARINO, MALI, FIJI, BELARUS (BYELORUSSIA), ERITREA, BHUTAN, ROMANIA, LIECHTENSTEIN, DENMARK, CHINA, INDONESIA, IRELAND, TAIWAN (REPUBLIC OF CHINA), KENYA, BOTSWANA, GUYANA, GEORGIA, KAZAKSTAN, HUNGARY, INDIA, CHILE, LESOTHO, ITALY, LATVIA, SAO TOME E PRINCIPE, THAILAND, YEMEN, SURINAME, DOMINICA, NORTH KOREA, RUSSIA, ARMENIA, BRUNEI, PORTUGAL, SWAZILAND, PAPUA NEW GUINEA, NEW ZEALAND, SIERRA LEONE, KYRGYZSTAN, UKRAINE, EGYPT, JORDAN, TOGO, MALAYSIA, RWANDA, MONGOLIA, UGANDA, MONTENEGRO, NIGERIA, THE GAMBIA, GUINEA, GHANA, CANADA, ST. VINCENT AND THE GRENADINES, BARBADOS, TURKEY, THE NETHERLANDS, WESTERN SAMOA, CYPRUS, CHAD, GRENADA, TUVALU, ZAMBIA, BOSNIA, UNITED ARAB EMIRATES, PALAU, MAURITIUS, LIBYA, ESTONIA, CENTRAL AFRICAN REPUBLIC, GERMANY, PANAMA, POLAND, LAOS, CROATIA, BISSAU, NICARAGUA, DJIBOUTI, MOROCCO, UNITED STATES OF AMERICA, NORWAY, MACEDONIA, GABON, EQUATORIAL GUINEA, PHILIPPINES]
Shuffled capitals: [Bandar Seri Begawan, Managua, Yaounde, Manila, Ulan Bator, Monrovia, Valletta, Luxembourg, San Marino, Vaduz, Colombo, Bogota, Kuala Lumpur, Ljuijana, Vilnius, Algiers, Yerevan, Minsk, Zagreb, Stockholm, Mexico City, Tashkent, Santiago, Bangui, Ouagadougou, Nuku'alofa, Freetown, Berne, Nouakchott, Islamabad, Tbilisi, Warsaw, Paramaribo, Saint John's, Seoul, Oslo, Mogadishu, Katmandu, New Delhi, Vientiane, Amsterdam, Sao Tome, Lisbon, P'yongyang, Nassau, Bucharest, Vienna, Asuncion, Ashkabad, Kuwait City, Tokyo, Kigali, Athens, Bamako, Abuja, Sofia, Malabo, Chisinau, Hanoi, Lusaka, Male, Bairiki, Porto-Novo, Palikir, Kabul, Phnom Penh, Skopje, Amman, Asmara, Port of Spain, Rabat, Belmopan, Pretoria/Cape Town, Honaira, Nicosia, Bissau, Niamey, N'djamena, < Port-Vila, Bridgetown, Nairobi, Berlin, Canberra, Banjul, Prague, Sucre (legal)/La Paz(administrative), San Salvador, Monaco, Windhoek, Tegucigalpa, Luanda, Addis Ababa, Montevideo, Damascus, Andorra la Vella, Tunis, Paris, Koror, Copenhagen, Guatemala City, Dijibouti, Basseterre, Wellington, Singapore, Dublin, Fongafale, Almaty, Conakry, Tehran, Victoria, Tallinn, Kingstown, Kyiv, Kinshasa, Dushanbe, Alma-Ata, Lima, Budapest, Lilongwe, Brussels, Kingston, Saint George's, Maputo, Georgetown, Gaberone, Abu Dhabi, Maseru, Thimphu, Antananarivo, Buenos Aires, San Jose, Caracas, Baku, Sarajevo, Yamoussoukro, Libreville, Brasilia, Dalap-Uliga-Darrit, Moscow, Tripoli, Riyadh, -, Manama, Ankara, Podgorica, Khartoum, Rangoon, Port Louis, Panama City, -, Washington, D.C., Port Moresby, Doha, Dodoma, Beirut, Port-au-Prince, Sana'a, Apia, Harare, Castries, Suva, Quito, Dhaka, Kampala, Reykjavik, Tirana, Brazzaville, Bujumbura, London, Ottawa, Jerusalem, Dakar, Moroni, Helsinki, Beijing, Cairo, Mbabane, Accra, Santo Domingo, Muscat, Riga, Jakarta, Taipei, Madrid, Praia, Havana, Bratislava, Roseau, Yaren, ---, Belgrade, Lome, Rome, Bangkok, Baghdad]
*/